# gitops-platform/infrastructure/base/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmaps/platform-endpoints.yaml
  - configmaps/traefik-config.yaml
  - secrets/postgres-credentials.yaml
  - secrets/rabbitmq-credentials.yaml
  - secrets/kafka-credentials.yaml
  - secrets/redis-credentials.yaml

labels:
  - pairs:
      component: infrastructure
      managed-by: gitops
    includeSelectors: false