apiVersion: v1
kind: ConfigMap
metadata:
  name: infrastructure-endpoints
data:
  POSTGRES_HOST: "postgres.infrastructure.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "authdb"
  
  REDIS_HOST: "redis-master.infrastructure.svc.cluster.local"
  REDIS_PORT: "6379"
  
  RABBITMQ_HOST: "rabbitmq.infrastructure.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VHOST: "microservice_one"
  
  KAFKA_BROKERS: "kafka.infrastructure.svc.cluster.local:9092"
  
  # Traefik service discovery
  TRAEFIK_SERVICE: "traefik.infrastructure.svc.cluster.local"